/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/neutralTheme.ts
 * Command: astryx theme build src/theme/neutralTheme.ts --out src/theme/theme.css
 * Generated: 2026-07-16T14:14:09.625Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const neutralTheme: DefinedTheme;
